services:

  order-service:
    build: ./Order-Service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ORDER_DATASOURCE_USERNAME=postgres
      - ORDER_DATASOURCE_PASSWORD=postgres
      - ORDER_RABBITMQ_USER=admin
      - ORDER_RABBITMQ_PASSWORD=admin123
    depends_on:
      orderdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    networks:
      - product-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  inventory-service:
    build: ./Inventory-Service
    container_name: inventory-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - INVENTORY_DATASOURCE_USERNAME=postgres
      - INVENTORY_DATASOURCE_PASSWORD=postgres
      - INVENTORY_RABBITMQ_USER=admin
      - INVENTORY_RABBITMQ_PASSWORD=admin123
    depends_on:
      inventorydb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
      order-service:
        condition: service_healthy
    networks:
      - product-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  payment-service:
    build: ./Payment-Service
    container_name: payment-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PAYMENT_DATASOURCE_USERNAME=postgres
      - PAYMENT_DATASOURCE_PASSWORD=postgres
      - PAYMENT_RABBITMQ_USER=admin
      - PAYMENT_RABBITMQ_PASSWORD=admin123
    depends_on:
      paymentdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
      order-service:
        condition: service_healthy
    networks:
      - product-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  service-discovery:
    build: ./Service-Discovery
    container_name: service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8761:8761"
    networks:
      - product-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  api-gateway:
    build: ./API-Gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      order-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - product-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  orderdb:
    image: postgres:16
    container_name: orderdb
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - product-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventorydb:
    image: postgres:16
    container_name: inventorydb
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - product-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  paymentdb:
    image: postgres:16
    container_name: paymentdb
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - product-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4order:
    image: dpage/pgadmin4
    container_name: pgadmin4order
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - orderdb
      - inventorydb
      - paymentdb
    networks:
      - product-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - product-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  product-network:
    driver: bridge