services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_order
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - product-network

networks:
  product-network:
    driver: bridge