spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/product/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payment/**
    inetutils:
      preferred-networks: 127.0.0.1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true