spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/product/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

---

# dev

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

---

#(prod)

spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    fetch-registry: true
    register-with-eureka: true