spring:
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
  application:
    name: Service-Discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
server:
  port: 8761
