spring:
  application:
    name: Payment-Service
  datasource:
    url: jdbc:postgresql://localhost:5434/paymentdb
    driver-class-name: org.postgresql.Driver
    username: ${PAYMENT_DATASOURCE_USERNAME}
    password: ${PAYMENT_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
server:
  port: 8083