spring:
  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0.1 #mudar depois
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5433/inventorydb
    driver-class-name: org.postgresql.Driver
    username: ${INVENTORY_DATASOURCE_USERNAME}
    password: ${INVENTORY_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8082